// Code generated by protoc-gen-go. DO NOT EDIT.
// source: props.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MiniGamePageType int32

const (
	MiniGamePageType_MINIGAME_SHOP_PAGE_UNDEFINE MiniGamePageType = 0
	MiniGamePageType_MINIGAME_SHOP_PAGE_HEAD     MiniGamePageType = 1
	MiniGamePageType_MINIGAME_SHOP_PAGE_PROP     MiniGamePageType = 2
	MiniGamePageType_MINIGAME_SHOP_PAGE_EXCHANGE MiniGamePageType = 3
	MiniGamePageType_MINIGAME_SHOP_PAGE_GOLD     MiniGamePageType = 4
	MiniGamePageType_MINIGAME_SHOP_PAGE_DIAMOND  MiniGamePageType = 5
)

var MiniGamePageType_name = map[int32]string{
	0: "MINIGAME_SHOP_PAGE_UNDEFINE",
	1: "MINIGAME_SHOP_PAGE_HEAD",
	2: "MINIGAME_SHOP_PAGE_PROP",
	3: "MINIGAME_SHOP_PAGE_EXCHANGE",
	4: "MINIGAME_SHOP_PAGE_GOLD",
	5: "MINIGAME_SHOP_PAGE_DIAMOND",
}

var MiniGamePageType_value = map[string]int32{
	"MINIGAME_SHOP_PAGE_UNDEFINE": 0,
	"MINIGAME_SHOP_PAGE_HEAD":     1,
	"MINIGAME_SHOP_PAGE_PROP":     2,
	"MINIGAME_SHOP_PAGE_EXCHANGE": 3,
	"MINIGAME_SHOP_PAGE_GOLD":     4,
	"MINIGAME_SHOP_PAGE_DIAMOND":  5,
}

func (x MiniGamePageType) Enum() *MiniGamePageType {
	p := new(MiniGamePageType)
	*p = x
	return p
}

func (x MiniGamePageType) String() string {
	return proto.EnumName(MiniGamePageType_name, int32(x))
}

func (x *MiniGamePageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MiniGamePageType_value, data, "MiniGamePageType")
	if err != nil {
		return err
	}
	*x = MiniGamePageType(value)
	return nil
}

func (MiniGamePageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{0}
}

type ProMiniGameShopPropListRequest_MSGID int32

const (
	ProMiniGameShopPropListRequest_ID ProMiniGameShopPropListRequest_MSGID = 660
)

var ProMiniGameShopPropListRequest_MSGID_name = map[int32]string{
	660: "ID",
}

var ProMiniGameShopPropListRequest_MSGID_value = map[string]int32{
	"ID": 660,
}

func (x ProMiniGameShopPropListRequest_MSGID) Enum() *ProMiniGameShopPropListRequest_MSGID {
	p := new(ProMiniGameShopPropListRequest_MSGID)
	*p = x
	return p
}

func (x ProMiniGameShopPropListRequest_MSGID) String() string {
	return proto.EnumName(ProMiniGameShopPropListRequest_MSGID_name, int32(x))
}

func (x *ProMiniGameShopPropListRequest_MSGID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProMiniGameShopPropListRequest_MSGID_value, data, "ProMiniGameShopPropListRequest_MSGID")
	if err != nil {
		return err
	}
	*x = ProMiniGameShopPropListRequest_MSGID(value)
	return nil
}

func (ProMiniGameShopPropListRequest_MSGID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{0, 0}
}

type ProMiniGameShopPropListRequest struct {
	MessageId            *int32            `protobuf:"varint,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	GameId               *int32            `protobuf:"varint,3,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	PlatformId           *int32            `protobuf:"varint,4,opt,name=platform_id,json=platformId" json:"platform_id,omitempty"`
	PageType             *MiniGamePageType `protobuf:"varint,5,opt,name=page_type,json=pageType,enum=messages.MiniGamePageType" json:"page_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProMiniGameShopPropListRequest) Reset()         { *m = ProMiniGameShopPropListRequest{} }
func (m *ProMiniGameShopPropListRequest) String() string { return proto.CompactTextString(m) }
func (*ProMiniGameShopPropListRequest) ProtoMessage()    {}
func (*ProMiniGameShopPropListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{0}
}

func (m *ProMiniGameShopPropListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProMiniGameShopPropListRequest.Unmarshal(m, b)
}
func (m *ProMiniGameShopPropListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProMiniGameShopPropListRequest.Marshal(b, m, deterministic)
}
func (m *ProMiniGameShopPropListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProMiniGameShopPropListRequest.Merge(m, src)
}
func (m *ProMiniGameShopPropListRequest) XXX_Size() int {
	return xxx_messageInfo_ProMiniGameShopPropListRequest.Size(m)
}
func (m *ProMiniGameShopPropListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProMiniGameShopPropListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProMiniGameShopPropListRequest proto.InternalMessageInfo

func (m *ProMiniGameShopPropListRequest) GetMessageId() int32 {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return 0
}

func (m *ProMiniGameShopPropListRequest) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *ProMiniGameShopPropListRequest) GetPlatformId() int32 {
	if m != nil && m.PlatformId != nil {
		return *m.PlatformId
	}
	return 0
}

func (m *ProMiniGameShopPropListRequest) GetPageType() MiniGamePageType {
	if m != nil && m.PageType != nil {
		return *m.PageType
	}
	return MiniGamePageType_MINIGAME_SHOP_PAGE_UNDEFINE
}

func init() {
	proto.RegisterEnum("messages.MiniGamePageType", MiniGamePageType_name, MiniGamePageType_value)
	proto.RegisterEnum("messages.ProMiniGameShopPropListRequest_MSGID", ProMiniGameShopPropListRequest_MSGID_name, ProMiniGameShopPropListRequest_MSGID_value)
	proto.RegisterType((*ProMiniGameShopPropListRequest)(nil), "messages.ProMiniGameShopPropListRequest")
}

func init() { proto.RegisterFile("props.proto", fileDescriptor_a3bd7ec71bb5ace1) }

var fileDescriptor_a3bd7ec71bb5ace1 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8e, 0xc1, 0x6a, 0xb3, 0x40,
	0x14, 0x85, 0x7f, 0x93, 0xf8, 0x27, 0xb9, 0x81, 0x32, 0xcc, 0x26, 0x21, 0xa1, 0x49, 0xc8, 0x2a,
	0x74, 0xe1, 0xa2, 0x9b, 0xae, 0xa5, 0x33, 0x1d, 0x07, 0xa2, 0x0e, 0xda, 0x42, 0x77, 0x22, 0x38,
	0xb5, 0x42, 0xed, 0x4c, 0x1d, 0xbb, 0xc8, 0x7b, 0xf4, 0x91, 0xba, 0xeb, 0x4b, 0x15, 0x45, 0x37,
	0x25, 0xee, 0xee, 0x3d, 0xdf, 0x39, 0x87, 0x03, 0x0b, 0x5d, 0x29, 0x6d, 0x1c, 0x5d, 0xa9, 0x5a,
	0xe1, 0x59, 0x29, 0x8d, 0x49, 0x73, 0x69, 0x0e, 0xdf, 0x16, 0x6c, 0x45, 0xa5, 0xfc, 0xe2, 0xbd,
	0x60, 0x69, 0x29, 0xe3, 0x57, 0xa5, 0x45, 0xa5, 0xf4, 0xa9, 0x30, 0x75, 0x24, 0x3f, 0x3e, 0xa5,
	0xa9, 0xf1, 0x35, 0x40, 0x67, 0x4f, 0x8a, 0x6c, 0x35, 0xda, 0x5b, 0x47, 0x3b, 0x9a, 0x77, 0x0a,
	0xcf, 0xf0, 0x12, 0xa6, 0x79, 0x5a, 0xb6, 0x6c, 0xdc, 0xb2, 0xff, 0xcd, 0xcb, 0x33, 0xbc, 0x83,
	0x85, 0x7e, 0x4b, 0xeb, 0x17, 0x55, 0x95, 0x0d, 0x9c, 0xb4, 0x10, 0x7a, 0x89, 0x67, 0xf8, 0x0e,
	0xe6, 0xba, 0x69, 0xad, 0xcf, 0x5a, 0xae, 0xec, 0xbd, 0x75, 0xbc, 0xba, 0x5d, 0x3b, 0xfd, 0x32,
	0xa7, 0x9f, 0x24, 0xd2, 0x5c, 0x3e, 0x9e, 0xb5, 0x8c, 0x66, 0xba, 0xbb, 0x0e, 0x08, 0x6c, 0x3f,
	0x66, 0x9c, 0xe0, 0x29, 0x8c, 0x38, 0x41, 0x5f, 0xf6, 0xcd, 0x8f, 0x05, 0xe8, 0x6f, 0x00, 0xef,
	0x60, 0xe3, 0xf3, 0x80, 0x33, 0xd7, 0xa7, 0x49, 0xec, 0x85, 0x22, 0x11, 0x2e, 0xa3, 0xc9, 0x53,
	0x40, 0xe8, 0x03, 0x0f, 0x28, 0xfa, 0x87, 0x37, 0xb0, 0xbc, 0x60, 0xf0, 0xa8, 0x4b, 0x90, 0x35,
	0x00, 0x45, 0x14, 0x0a, 0x34, 0x1a, 0xa8, 0xa6, 0xcf, 0xf7, 0x9e, 0x1b, 0x30, 0x8a, 0xc6, 0x03,
	0x69, 0x16, 0x9e, 0x08, 0x9a, 0xe0, 0x2d, 0xac, 0x2f, 0x40, 0xc2, 0x5d, 0x3f, 0x0c, 0x08, 0xb2,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xc5, 0x2d, 0x92, 0xac, 0x01, 0x00, 0x00,
}
