// Code generated by protoc-gen-go. DO NOT EDIT
// source: props.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MiniGamePageType int32

const (
	MiniGamePageType_MINIGAME_SHOP_PAGE_UNDEFINE MiniGamePageType = 0
	MiniGamePageType_MINIGAME_SHOP_PAGE_HEAD     MiniGamePageType = 1
	MiniGamePageType_MINIGAME_SHOP_PAGE_PROP     MiniGamePageType = 2
	MiniGamePageType_MINIGAME_SHOP_PAGE_EXCHANGE MiniGamePageType = 3
)

var MiniGamePageType_name = map[int32]string{
	0: "MINIGAME_SHOP_PAGE_UNDEFINE",
	1: "MINIGAME_SHOP_PAGE_HEAD",
	2: "MINIGAME_SHOP_PAGE_PROP",
	3: "MINIGAME_SHOP_PAGE_EXCHANGE",
}

var MiniGamePageType_value = map[string]int32{
	"MINIGAME_SHOP_PAGE_UNDEFINE": 0,
	"MINIGAME_SHOP_PAGE_HEAD":     1,
	"MINIGAME_SHOP_PAGE_PROP":     2,
	"MINIGAME_SHOP_PAGE_EXCHANGE": 3,
}

func (x MiniGamePageType) Enum() *MiniGamePageType {
	p := new(MiniGamePageType)
	*p = x
	return p
}

func (x MiniGamePageType) String() string {
	return proto.EnumName(MiniGamePageType_name, int32(x))
}

func (x *MiniGamePageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MiniGamePageType_value, data, "MiniGamePageType")
	if err != nil {
		return err
	}
	*x = MiniGamePageType(value)
	return nil
}

func (MiniGamePageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{0}
}

type MiniGamePropAddTimeType int32

const (
	MiniGamePropAddTimeType_MINIGAME_PROP_UNDEFINE MiniGamePropAddTimeType = 0
	MiniGamePropAddTimeType_MINIGAME_PROP_HOUR     MiniGamePropAddTimeType = 1
	MiniGamePropAddTimeType_MINIGAME_PROP_DAY      MiniGamePropAddTimeType = 2
	MiniGamePropAddTimeType_MINIGAME_PROP_MONTH    MiniGamePropAddTimeType = 3
)

var MiniGamePropAddTimeType_name = map[int32]string{
	0: "MINIGAME_PROP_UNDEFINE",
	1: "MINIGAME_PROP_HOUR",
	2: "MINIGAME_PROP_DAY",
	3: "MINIGAME_PROP_MONTH",
}

var MiniGamePropAddTimeType_value = map[string]int32{
	"MINIGAME_PROP_UNDEFINE": 0,
	"MINIGAME_PROP_HOUR":     1,
	"MINIGAME_PROP_DAY":      2,
	"MINIGAME_PROP_MONTH":    3,
}

func (x MiniGamePropAddTimeType) Enum() *MiniGamePropAddTimeType {
	p := new(MiniGamePropAddTimeType)
	*p = x
	return p
}

func (x MiniGamePropAddTimeType) String() string {
	return proto.EnumName(MiniGamePropAddTimeType_name, int32(x))
}

func (x *MiniGamePropAddTimeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MiniGamePropAddTimeType_value, data, "MiniGamePropAddTimeType")
	if err != nil {
		return err
	}
	*x = MiniGamePropAddTimeType(value)
	return nil
}

func (MiniGamePropAddTimeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{1}
}

type MiniGamePropAddType int32

const (
	MiniGamePropAddType_MINIGAME_PROP_ADD_TYPE_UNDEFINE MiniGamePropAddType = 0
	MiniGamePropAddType_MINIGAME_PROP_ADD_TYPE_SHOP     MiniGamePropAddType = 1
	MiniGamePropAddType_MINIGAME_PROP_ADD_TYPE_EXCHANGE MiniGamePropAddType = 2
)

var MiniGamePropAddType_name = map[int32]string{
	0: "MINIGAME_PROP_ADD_TYPE_UNDEFINE",
	1: "MINIGAME_PROP_ADD_TYPE_SHOP",
	2: "MINIGAME_PROP_ADD_TYPE_EXCHANGE",
}

var MiniGamePropAddType_value = map[string]int32{
	"MINIGAME_PROP_ADD_TYPE_UNDEFINE": 0,
	"MINIGAME_PROP_ADD_TYPE_SHOP":     1,
	"MINIGAME_PROP_ADD_TYPE_EXCHANGE": 2,
}

func (x MiniGamePropAddType) Enum() *MiniGamePropAddType {
	p := new(MiniGamePropAddType)
	*p = x
	return p
}

func (x MiniGamePropAddType) String() string {
	return proto.EnumName(MiniGamePropAddType_name, int32(x))
}

func (x *MiniGamePropAddType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MiniGamePropAddType_value, data, "MiniGamePropAddType")
	if err != nil {
		return err
	}
	*x = MiniGamePropAddType(value)
	return nil
}

func (MiniGamePropAddType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{2}
}

type ProMiniGameShopPropListRequest_MSGID int32

const (
	ProMiniGameShopPropListRequest_ID ProMiniGameShopPropListRequest_MSGID = 660
)

var ProMiniGameShopPropListRequest_MSGID_name = map[int32]string{
	660: "ID",
}

var ProMiniGameShopPropListRequest_MSGID_value = map[string]int32{
	"ID": 660,
}

func (x ProMiniGameShopPropListRequest_MSGID) Enum() *ProMiniGameShopPropListRequest_MSGID {
	p := new(ProMiniGameShopPropListRequest_MSGID)
	*p = x
	return p
}

func (x ProMiniGameShopPropListRequest_MSGID) String() string {
	return proto.EnumName(ProMiniGameShopPropListRequest_MSGID_name, int32(x))
}

func (x *ProMiniGameShopPropListRequest_MSGID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProMiniGameShopPropListRequest_MSGID_value, data, "ProMiniGameShopPropListRequest_MSGID")
	if err != nil {
		return err
	}
	*x = ProMiniGameShopPropListRequest_MSGID(value)
	return nil
}

func (ProMiniGameShopPropListRequest_MSGID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{0, 0}
}

type ProMiniGameShopPropListResponse_MSGID int32

const (
	ProMiniGameShopPropListResponse_ID ProMiniGameShopPropListResponse_MSGID = 661
)

var ProMiniGameShopPropListResponse_MSGID_name = map[int32]string{
	661: "ID",
}

var ProMiniGameShopPropListResponse_MSGID_value = map[string]int32{
	"ID": 661,
}

func (x ProMiniGameShopPropListResponse_MSGID) Enum() *ProMiniGameShopPropListResponse_MSGID {
	p := new(ProMiniGameShopPropListResponse_MSGID)
	*p = x
	return p
}

func (x ProMiniGameShopPropListResponse_MSGID) String() string {
	return proto.EnumName(ProMiniGameShopPropListResponse_MSGID_name, int32(x))
}

func (x *ProMiniGameShopPropListResponse_MSGID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProMiniGameShopPropListResponse_MSGID_value, data, "ProMiniGameShopPropListResponse_MSGID")
	if err != nil {
		return err
	}
	*x = ProMiniGameShopPropListResponse_MSGID(value)
	return nil
}

func (ProMiniGameShopPropListResponse_MSGID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{1, 0}
}

type ProMiniGamePropExchangeRequest_MSGID int32

const (
	ProMiniGamePropExchangeRequest_ID ProMiniGamePropExchangeRequest_MSGID = 662
)

var ProMiniGamePropExchangeRequest_MSGID_name = map[int32]string{
	662: "ID",
}

var ProMiniGamePropExchangeRequest_MSGID_value = map[string]int32{
	"ID": 662,
}

func (x ProMiniGamePropExchangeRequest_MSGID) Enum() *ProMiniGamePropExchangeRequest_MSGID {
	p := new(ProMiniGamePropExchangeRequest_MSGID)
	*p = x
	return p
}

func (x ProMiniGamePropExchangeRequest_MSGID) String() string {
	return proto.EnumName(ProMiniGamePropExchangeRequest_MSGID_name, int32(x))
}

func (x *ProMiniGamePropExchangeRequest_MSGID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProMiniGamePropExchangeRequest_MSGID_value, data, "ProMiniGamePropExchangeRequest_MSGID")
	if err != nil {
		return err
	}
	*x = ProMiniGamePropExchangeRequest_MSGID(value)
	return nil
}

func (ProMiniGamePropExchangeRequest_MSGID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{2, 0}
}

type ProMiniGamePropExchangeResponse_MSGID int32

const (
	ProMiniGamePropExchangeResponse_ID ProMiniGamePropExchangeResponse_MSGID = 663
)

var ProMiniGamePropExchangeResponse_MSGID_name = map[int32]string{
	663: "ID",
}

var ProMiniGamePropExchangeResponse_MSGID_value = map[string]int32{
	"ID": 663,
}

func (x ProMiniGamePropExchangeResponse_MSGID) Enum() *ProMiniGamePropExchangeResponse_MSGID {
	p := new(ProMiniGamePropExchangeResponse_MSGID)
	*p = x
	return p
}

func (x ProMiniGamePropExchangeResponse_MSGID) String() string {
	return proto.EnumName(ProMiniGamePropExchangeResponse_MSGID_name, int32(x))
}

func (x *ProMiniGamePropExchangeResponse_MSGID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProMiniGamePropExchangeResponse_MSGID_value, data, "ProMiniGamePropExchangeResponse_MSGID")
	if err != nil {
		return err
	}
	*x = ProMiniGamePropExchangeResponse_MSGID(value)
	return nil
}

func (ProMiniGamePropExchangeResponse_MSGID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{3, 0}
}

// MiniGameShopPropListRequest 商城道具列表请求
type ProMiniGameShopPropListRequest struct {
	MessageId            *int32            `protobuf:"varint,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	GameId               *int32            `protobuf:"varint,3,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	PlatformId           *int32            `protobuf:"varint,4,opt,name=platform_id,json=platformId" json:"platform_id,omitempty"`
	PageType             *MiniGamePageType `protobuf:"varint,5,opt,name=page_type,json=pageType,enum=messages.MiniGamePageType" json:"page_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProMiniGameShopPropListRequest) Reset()         { *m = ProMiniGameShopPropListRequest{} }
func (m *ProMiniGameShopPropListRequest) String() string { return proto.CompactTextString(m) }
func (*ProMiniGameShopPropListRequest) ProtoMessage()    {}
func (*ProMiniGameShopPropListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{0}
}

func (m *ProMiniGameShopPropListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProMiniGameShopPropListRequest.Unmarshal(m, b)
}
func (m *ProMiniGameShopPropListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProMiniGameShopPropListRequest.Marshal(b, m, deterministic)
}
func (m *ProMiniGameShopPropListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProMiniGameShopPropListRequest.Merge(m, src)
}
func (m *ProMiniGameShopPropListRequest) XXX_Size() int {
	return xxx_messageInfo_ProMiniGameShopPropListRequest.Size(m)
}
func (m *ProMiniGameShopPropListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProMiniGameShopPropListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProMiniGameShopPropListRequest proto.InternalMessageInfo

func (m *ProMiniGameShopPropListRequest) GetMessageId() int32 {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return 0
}

func (m *ProMiniGameShopPropListRequest) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *ProMiniGameShopPropListRequest) GetPlatformId() int32 {
	if m != nil && m.PlatformId != nil {
		return *m.PlatformId
	}
	return 0
}

func (m *ProMiniGameShopPropListRequest) GetPageType() MiniGamePageType {
	if m != nil && m.PageType != nil {
		return *m.PageType
	}
	return MiniGamePageType_MINIGAME_SHOP_PAGE_UNDEFINE
}

// MiniGameShopPropListResponse 商城道具列表响应
type ProMiniGameShopPropListResponse struct {
	MessageId            *int32                  `protobuf:"varint,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	Message              *string                 `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Status               *int32                  `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`
	PageType             *MiniGamePageType       `protobuf:"varint,5,opt,name=page_type,json=pageType,enum=messages.MiniGamePageType" json:"page_type,omitempty"`
	ShopPropInfo         []*MiniGameShopPropInfo `protobuf:"bytes,6,rep,name=shop_prop_info,json=shopPropInfo" json:"shop_prop_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ProMiniGameShopPropListResponse) Reset()         { *m = ProMiniGameShopPropListResponse{} }
func (m *ProMiniGameShopPropListResponse) String() string { return proto.CompactTextString(m) }
func (*ProMiniGameShopPropListResponse) ProtoMessage()    {}
func (*ProMiniGameShopPropListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{1}
}

func (m *ProMiniGameShopPropListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProMiniGameShopPropListResponse.Unmarshal(m, b)
}
func (m *ProMiniGameShopPropListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProMiniGameShopPropListResponse.Marshal(b, m, deterministic)
}
func (m *ProMiniGameShopPropListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProMiniGameShopPropListResponse.Merge(m, src)
}
func (m *ProMiniGameShopPropListResponse) XXX_Size() int {
	return xxx_messageInfo_ProMiniGameShopPropListResponse.Size(m)
}
func (m *ProMiniGameShopPropListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProMiniGameShopPropListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProMiniGameShopPropListResponse proto.InternalMessageInfo

func (m *ProMiniGameShopPropListResponse) GetMessageId() int32 {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return 0
}

func (m *ProMiniGameShopPropListResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *ProMiniGameShopPropListResponse) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *ProMiniGameShopPropListResponse) GetPageType() MiniGamePageType {
	if m != nil && m.PageType != nil {
		return *m.PageType
	}
	return MiniGamePageType_MINIGAME_SHOP_PAGE_UNDEFINE
}

func (m *ProMiniGameShopPropListResponse) GetShopPropInfo() []*MiniGameShopPropInfo {
	if m != nil {
		return m.ShopPropInfo
	}
	return nil
}

// MiniGamePropExchangeRequest 商城兑换请求
type ProMiniGamePropExchangeRequest struct {
	MessageId            *int32               `protobuf:"varint,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	GameId               *int32               `protobuf:"varint,3,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	PlatformId           *int32               `protobuf:"varint,4,opt,name=platform_id,json=platformId" json:"platform_id,omitempty"`
	UserId               *int32               `protobuf:"varint,5,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ShopConfigId         *int32               `protobuf:"varint,6,opt,name=shop_config_id,json=shopConfigId" json:"shop_config_id,omitempty"`
	PropConfigId         *int32               `protobuf:"varint,7,opt,name=prop_config_id,json=propConfigId" json:"prop_config_id,omitempty"`
	PropNum              *int32               `protobuf:"varint,8,opt,name=prop_num,json=propNum" json:"prop_num,omitempty"`
	UsedCoinType         *int32               `protobuf:"varint,9,opt,name=used_coin_type,json=usedCoinType" json:"used_coin_type,omitempty"`
	PropPageType         *MiniGamePageType    `protobuf:"varint,10,opt,name=prop_page_type,json=propPageType,enum=messages.MiniGamePageType" json:"prop_page_type,omitempty"`
	PropAddType          *MiniGamePropAddType `protobuf:"varint,11,opt,name=prop_add_type,json=propAddType,enum=messages.MiniGamePropAddType" json:"prop_add_type,omitempty"`
	PropTimeNum          *int32               `protobuf:"varint,12,opt,name=prop_time_num,json=propTimeNum" json:"prop_time_num,omitempty"`
	UserPhoneAddr        []byte               `protobuf:"bytes,13,opt,name=user_phone_addr,json=userPhoneAddr" json:"user_phone_addr,omitempty"`
	UsedCoinNum          *int32               `protobuf:"varint,14,opt,name=used_coin_num,json=usedCoinNum" json:"used_coin_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProMiniGamePropExchangeRequest) Reset()         { *m = ProMiniGamePropExchangeRequest{} }
func (m *ProMiniGamePropExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*ProMiniGamePropExchangeRequest) ProtoMessage()    {}
func (*ProMiniGamePropExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{2}
}

func (m *ProMiniGamePropExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProMiniGamePropExchangeRequest.Unmarshal(m, b)
}
func (m *ProMiniGamePropExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProMiniGamePropExchangeRequest.Marshal(b, m, deterministic)
}
func (m *ProMiniGamePropExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProMiniGamePropExchangeRequest.Merge(m, src)
}
func (m *ProMiniGamePropExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_ProMiniGamePropExchangeRequest.Size(m)
}
func (m *ProMiniGamePropExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProMiniGamePropExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProMiniGamePropExchangeRequest proto.InternalMessageInfo

func (m *ProMiniGamePropExchangeRequest) GetMessageId() int32 {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return 0
}

func (m *ProMiniGamePropExchangeRequest) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *ProMiniGamePropExchangeRequest) GetPlatformId() int32 {
	if m != nil && m.PlatformId != nil {
		return *m.PlatformId
	}
	return 0
}

func (m *ProMiniGamePropExchangeRequest) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *ProMiniGamePropExchangeRequest) GetShopConfigId() int32 {
	if m != nil && m.ShopConfigId != nil {
		return *m.ShopConfigId
	}
	return 0
}

func (m *ProMiniGamePropExchangeRequest) GetPropConfigId() int32 {
	if m != nil && m.PropConfigId != nil {
		return *m.PropConfigId
	}
	return 0
}

func (m *ProMiniGamePropExchangeRequest) GetPropNum() int32 {
	if m != nil && m.PropNum != nil {
		return *m.PropNum
	}
	return 0
}

func (m *ProMiniGamePropExchangeRequest) GetUsedCoinType() int32 {
	if m != nil && m.UsedCoinType != nil {
		return *m.UsedCoinType
	}
	return 0
}

func (m *ProMiniGamePropExchangeRequest) GetPropPageType() MiniGamePageType {
	if m != nil && m.PropPageType != nil {
		return *m.PropPageType
	}
	return MiniGamePageType_MINIGAME_SHOP_PAGE_UNDEFINE
}

func (m *ProMiniGamePropExchangeRequest) GetPropAddType() MiniGamePropAddType {
	if m != nil && m.PropAddType != nil {
		return *m.PropAddType
	}
	return MiniGamePropAddType_MINIGAME_PROP_ADD_TYPE_UNDEFINE
}

func (m *ProMiniGamePropExchangeRequest) GetPropTimeNum() int32 {
	if m != nil && m.PropTimeNum != nil {
		return *m.PropTimeNum
	}
	return 0
}

func (m *ProMiniGamePropExchangeRequest) GetUserPhoneAddr() []byte {
	if m != nil {
		return m.UserPhoneAddr
	}
	return nil
}

func (m *ProMiniGamePropExchangeRequest) GetUsedCoinNum() int32 {
	if m != nil && m.UsedCoinNum != nil {
		return *m.UsedCoinNum
	}
	return 0
}

// ExchangeResponse 商城兑换相应响应
// message_id = 663
type ProMiniGamePropExchangeResponse struct {
	MessageId            *int32   `protobuf:"varint,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	Message              *string  `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Status               *int32   `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProMiniGamePropExchangeResponse) Reset()         { *m = ProMiniGamePropExchangeResponse{} }
func (m *ProMiniGamePropExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*ProMiniGamePropExchangeResponse) ProtoMessage()    {}
func (*ProMiniGamePropExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{3}
}

func (m *ProMiniGamePropExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProMiniGamePropExchangeResponse.Unmarshal(m, b)
}
func (m *ProMiniGamePropExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProMiniGamePropExchangeResponse.Marshal(b, m, deterministic)
}
func (m *ProMiniGamePropExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProMiniGamePropExchangeResponse.Merge(m, src)
}
func (m *ProMiniGamePropExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_ProMiniGamePropExchangeResponse.Size(m)
}
func (m *ProMiniGamePropExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProMiniGamePropExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProMiniGamePropExchangeResponse proto.InternalMessageInfo

func (m *ProMiniGamePropExchangeResponse) GetMessageId() int32 {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return 0
}

func (m *ProMiniGamePropExchangeResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *ProMiniGamePropExchangeResponse) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

// MiniGamePropInfo 商城道具信息
type MiniGameShopPropInfo struct {
	Id                   *int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	GameId               *int32   `protobuf:"varint,2,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	PlatformId           *int32   `protobuf:"varint,3,opt,name=platform_id,json=platformId" json:"platform_id,omitempty"`
	PageType             *int32   `protobuf:"varint,4,opt,name=page_type,json=pageType" json:"page_type,omitempty"`
	PropConfigId         *int32   `protobuf:"varint,5,opt,name=prop_config_id,json=propConfigId" json:"prop_config_id,omitempty"`
	PropPriceMeal        []byte   `protobuf:"bytes,6,opt,name=prop_price_meal,json=propPriceMeal" json:"prop_price_meal,omitempty"`
	Position             *int32   `protobuf:"varint,7,opt,name=position" json:"position,omitempty"`
	Status               *int32   `protobuf:"varint,8,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MiniGameShopPropInfo) Reset()         { *m = MiniGameShopPropInfo{} }
func (m *MiniGameShopPropInfo) String() string { return proto.CompactTextString(m) }
func (*MiniGameShopPropInfo) ProtoMessage()    {}
func (*MiniGameShopPropInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{4}
}

func (m *MiniGameShopPropInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MiniGameShopPropInfo.Unmarshal(m, b)
}
func (m *MiniGameShopPropInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MiniGameShopPropInfo.Marshal(b, m, deterministic)
}
func (m *MiniGameShopPropInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiniGameShopPropInfo.Merge(m, src)
}
func (m *MiniGameShopPropInfo) XXX_Size() int {
	return xxx_messageInfo_MiniGameShopPropInfo.Size(m)
}
func (m *MiniGameShopPropInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MiniGameShopPropInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MiniGameShopPropInfo proto.InternalMessageInfo

func (m *MiniGameShopPropInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MiniGameShopPropInfo) GetGameId() int32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *MiniGameShopPropInfo) GetPlatformId() int32 {
	if m != nil && m.PlatformId != nil {
		return *m.PlatformId
	}
	return 0
}

func (m *MiniGameShopPropInfo) GetPageType() int32 {
	if m != nil && m.PageType != nil {
		return *m.PageType
	}
	return 0
}

func (m *MiniGameShopPropInfo) GetPropConfigId() int32 {
	if m != nil && m.PropConfigId != nil {
		return *m.PropConfigId
	}
	return 0
}

func (m *MiniGameShopPropInfo) GetPropPriceMeal() []byte {
	if m != nil {
		return m.PropPriceMeal
	}
	return nil
}

func (m *MiniGameShopPropInfo) GetPosition() int32 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *MiniGameShopPropInfo) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

// MiniGamePropExchangeLogInfo 商城兑换记录
type MiniGamePropExchangeLogInfo struct {
	ExchangeTime         *int32   `protobuf:"varint,1,opt,name=exchange_time,json=exchangeTime" json:"exchange_time,omitempty"`
	ExchangeName         []byte   `protobuf:"bytes,2,opt,name=exchange_name,json=exchangeName" json:"exchange_name,omitempty"`
	ExchangeNum          *int32   `protobuf:"varint,3,opt,name=exchange_num,json=exchangeNum" json:"exchange_num,omitempty"`
	ExchangePrice        *int32   `protobuf:"varint,4,opt,name=exchange_price,json=exchangePrice" json:"exchange_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MiniGamePropExchangeLogInfo) Reset()         { *m = MiniGamePropExchangeLogInfo{} }
func (m *MiniGamePropExchangeLogInfo) String() string { return proto.CompactTextString(m) }
func (*MiniGamePropExchangeLogInfo) ProtoMessage()    {}
func (*MiniGamePropExchangeLogInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3bd7ec71bb5ace1, []int{5}
}

func (m *MiniGamePropExchangeLogInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MiniGamePropExchangeLogInfo.Unmarshal(m, b)
}
func (m *MiniGamePropExchangeLogInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MiniGamePropExchangeLogInfo.Marshal(b, m, deterministic)
}
func (m *MiniGamePropExchangeLogInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiniGamePropExchangeLogInfo.Merge(m, src)
}
func (m *MiniGamePropExchangeLogInfo) XXX_Size() int {
	return xxx_messageInfo_MiniGamePropExchangeLogInfo.Size(m)
}
func (m *MiniGamePropExchangeLogInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MiniGamePropExchangeLogInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MiniGamePropExchangeLogInfo proto.InternalMessageInfo

func (m *MiniGamePropExchangeLogInfo) GetExchangeTime() int32 {
	if m != nil && m.ExchangeTime != nil {
		return *m.ExchangeTime
	}
	return 0
}

func (m *MiniGamePropExchangeLogInfo) GetExchangeName() []byte {
	if m != nil {
		return m.ExchangeName
	}
	return nil
}

func (m *MiniGamePropExchangeLogInfo) GetExchangeNum() int32 {
	if m != nil && m.ExchangeNum != nil {
		return *m.ExchangeNum
	}
	return 0
}

func (m *MiniGamePropExchangeLogInfo) GetExchangePrice() int32 {
	if m != nil && m.ExchangePrice != nil {
		return *m.ExchangePrice
	}
	return 0
}

func init() {
	proto.RegisterEnum("messages.MiniGamePageType", MiniGamePageType_name, MiniGamePageType_value)
	proto.RegisterEnum("messages.MiniGamePropAddTimeType", MiniGamePropAddTimeType_name, MiniGamePropAddTimeType_value)
	proto.RegisterEnum("messages.MiniGamePropAddType", MiniGamePropAddType_name, MiniGamePropAddType_value)
	proto.RegisterEnum("messages.ProMiniGameShopPropListRequest_MSGID", ProMiniGameShopPropListRequest_MSGID_name, ProMiniGameShopPropListRequest_MSGID_value)
	proto.RegisterEnum("messages.ProMiniGameShopPropListResponse_MSGID", ProMiniGameShopPropListResponse_MSGID_name, ProMiniGameShopPropListResponse_MSGID_value)
	proto.RegisterEnum("messages.ProMiniGamePropExchangeRequest_MSGID", ProMiniGamePropExchangeRequest_MSGID_name, ProMiniGamePropExchangeRequest_MSGID_value)
	proto.RegisterEnum("messages.ProMiniGamePropExchangeResponse_MSGID", ProMiniGamePropExchangeResponse_MSGID_name, ProMiniGamePropExchangeResponse_MSGID_value)
	proto.RegisterType((*ProMiniGameShopPropListRequest)(nil), "messages.ProMiniGameShopPropListRequest")
	proto.RegisterType((*ProMiniGameShopPropListResponse)(nil), "messages.ProMiniGameShopPropListResponse")
	proto.RegisterType((*ProMiniGamePropExchangeRequest)(nil), "messages.ProMiniGamePropExchangeRequest")
	proto.RegisterType((*ProMiniGamePropExchangeResponse)(nil), "messages.ProMiniGamePropExchangeResponse")
	proto.RegisterType((*MiniGameShopPropInfo)(nil), "messages.MiniGameShopPropInfo")
	proto.RegisterType((*MiniGamePropExchangeLogInfo)(nil), "messages.MiniGamePropExchangeLogInfo")
}

func init() { proto.RegisterFile("props.proto", fileDescriptor_a3bd7ec71bb5ace1) }

var fileDescriptor_a3bd7ec71bb5ace1 = []byte{
	// 787 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x4b, 0x4f, 0xf3, 0x56,
	0x10, 0xad, 0x1d, 0x9c, 0xc7, 0xe4, 0x81, 0x7b, 0x69, 0x49, 0x4a, 0x04, 0x49, 0x43, 0x8b, 0x22,
	0x16, 0x2c, 0xd8, 0x74, 0x5b, 0x0b, 0xbb, 0x89, 0x25, 0xe2, 0x58, 0x26, 0x48, 0x65, 0x65, 0x59,
	0xf1, 0x4d, 0x72, 0x25, 0xec, 0xeb, 0xfa, 0x21, 0x95, 0x45, 0xa5, 0x4a, 0xed, 0xba, 0xab, 0x3e,
	0xfe, 0x41, 0xf7, 0xfd, 0x0f, 0xfd, 0x5f, 0xdf, 0xa7, 0x7b, 0x6d, 0x27, 0x71, 0x08, 0x20, 0x7d,
	0x12, 0x3b, 0xcf, 0xcc, 0xb9, 0xc7, 0x73, 0x66, 0xce, 0x40, 0x3d, 0x08, 0x69, 0x10, 0x5d, 0x05,
	0x21, 0x8d, 0x29, 0xaa, 0x7a, 0x38, 0x8a, 0x9c, 0x25, 0x8e, 0x06, 0xff, 0x0b, 0x70, 0x66, 0x86,
	0x74, 0x42, 0x7c, 0x32, 0x72, 0x3c, 0x7c, 0xb7, 0xa2, 0x81, 0x19, 0xd2, 0xe0, 0x96, 0x44, 0xb1,
	0x85, 0x7f, 0x4a, 0x70, 0x14, 0xa3, 0x53, 0x80, 0x0c, 0x6e, 0x13, 0xb7, 0x23, 0xf6, 0x85, 0xa1,
	0x64, 0xd5, 0xb2, 0x8c, 0xee, 0xa2, 0x36, 0x54, 0x96, 0x8e, 0xc7, 0x6b, 0x25, 0x5e, 0x2b, 0xb3,
	0x50, 0x77, 0x51, 0x0f, 0xea, 0xc1, 0xa3, 0x13, 0x2f, 0x68, 0xe8, 0xb1, 0xe2, 0x01, 0x2f, 0x42,
	0x9e, 0xd2, 0x5d, 0xf4, 0x1d, 0xd4, 0x02, 0xc6, 0x1a, 0x3f, 0x05, 0xb8, 0x23, 0xf5, 0x85, 0x61,
	0xeb, 0xfa, 0xe4, 0x2a, 0xef, 0xec, 0x2a, 0x6f, 0xc9, 0x74, 0x96, 0x78, 0xf6, 0x14, 0x60, 0xab,
	0x1a, 0x64, 0x5f, 0x03, 0x19, 0xa4, 0xc9, 0xdd, 0x48, 0x57, 0x51, 0x05, 0x44, 0x5d, 0x95, 0xff,
	0x94, 0x06, 0xbf, 0x89, 0xd0, 0x7b, 0x51, 0x46, 0x14, 0x50, 0x3f, 0xc2, 0x6f, 0xe9, 0xe8, 0x40,
	0x25, 0x0b, 0xb8, 0x8e, 0x9a, 0x95, 0x87, 0xe8, 0x18, 0xca, 0x51, 0xec, 0xc4, 0x49, 0x94, 0x69,
	0xc8, 0xa2, 0x4f, 0xee, 0x1f, 0xa9, 0xd0, 0x8a, 0x56, 0x34, 0xb0, 0xd9, 0x4a, 0x6c, 0xe2, 0x2f,
	0x68, 0xa7, 0xdc, 0x2f, 0x0d, 0xeb, 0xd7, 0x67, 0xcf, 0x5f, 0xe7, 0x4a, 0x74, 0x7f, 0x41, 0xad,
	0x46, 0xb4, 0x15, 0xed, 0x4e, 0xe1, 0x2f, 0x69, 0xf0, 0xef, 0x41, 0x61, 0x99, 0x0c, 0xa9, 0xfd,
	0x3c, 0x5f, 0x39, 0xfe, 0x12, 0xbf, 0xfb, 0x32, 0xdb, 0x50, 0x49, 0x22, 0x1c, 0xb2, 0xa2, 0x94,
	0xbe, 0x64, 0xa1, 0xee, 0xa2, 0x6f, 0x32, 0xb1, 0x73, 0xea, 0x2f, 0xc8, 0x92, 0xd5, 0xcb, 0xbc,
	0xce, 0xc5, 0xdc, 0xf0, 0x64, 0x8a, 0xe2, 0xd3, 0xd8, 0xa0, 0x2a, 0x29, 0x8a, 0x65, 0xd7, 0xa8,
	0xaf, 0xa0, 0xca, 0x51, 0x7e, 0xe2, 0x75, 0xaa, 0xbc, 0x5e, 0x61, 0xb1, 0x91, 0x78, 0x8c, 0x20,
	0x89, 0xb0, 0x6b, 0xcf, 0x29, 0xf1, 0xd3, 0x8d, 0xd4, 0x52, 0x02, 0x96, 0xbd, 0xa1, 0xc4, 0xe7,
	0x93, 0xff, 0x3e, 0xfb, 0xcd, 0x66, 0x6f, 0xf0, 0xe6, 0xde, 0x78, 0x0b, 0x79, 0x84, 0x14, 0x68,
	0x72, 0x06, 0xc7, 0x75, 0x53, 0x82, 0x3a, 0x27, 0x38, 0xdd, 0x43, 0x10, 0xd2, 0x40, 0x71, 0x5d,
	0xce, 0xc1, 0xaf, 0x2f, 0x0b, 0xd0, 0x20, 0xa3, 0x88, 0x89, 0x87, 0xb9, 0x94, 0x06, 0xef, 0x94,
	0x63, 0x66, 0xc4, 0xc3, 0x4c, 0xce, 0x05, 0x1c, 0xf2, 0x71, 0x06, 0x2b, 0xea, 0x63, 0xf6, 0xb3,
	0xb0, 0xd3, 0xec, 0x0b, 0xc3, 0x86, 0xd5, 0x64, 0x69, 0x93, 0x65, 0x15, 0xd7, 0x0d, 0x19, 0xd7,
	0x46, 0x36, 0xe3, 0x6a, 0xa5, 0x5c, 0xb9, 0x6a, 0x23, 0xf1, 0x76, 0x8d, 0xf2, 0xb7, 0x34, 0xf8,
	0x5d, 0x28, 0x9c, 0x4b, 0xd1, 0x28, 0xef, 0x74, 0x2e, 0xbb, 0x6d, 0xfc, 0x23, 0x0d, 0x3e, 0x08,
	0xf0, 0xc5, 0x3e, 0xa3, 0xa3, 0x16, 0x88, 0xc4, 0xed, 0x08, 0xfc, 0xb9, 0x48, 0x0a, 0xb6, 0x14,
	0x5f, 0xb3, 0x65, 0xe9, 0x99, 0x2d, 0xbb, 0xdb, 0x37, 0x9a, 0xf6, 0xb3, 0xb9, 0xc3, 0xe7, 0xa6,
	0x93, 0xf6, 0x98, 0xee, 0x02, 0x0e, 0x53, 0xcf, 0x84, 0x64, 0x8e, 0x6d, 0x0f, 0x3b, 0x8f, 0xdc,
	0xc1, 0x0d, 0x8b, 0x6f, 0xd1, 0x64, 0xd9, 0x09, 0x76, 0x1e, 0xd1, 0x09, 0x54, 0x03, 0x1a, 0x91,
	0x98, 0x50, 0x3f, 0x33, 0xef, 0x3a, 0xde, 0x9a, 0x49, 0xb5, 0x30, 0x93, 0xff, 0x04, 0xe8, 0xee,
	0xdb, 0xc2, 0x2d, 0x5d, 0xf2, 0x41, 0x9c, 0x43, 0x13, 0x67, 0x29, 0x6e, 0x97, 0x6c, 0x26, 0x8d,
	0x3c, 0xc9, 0xec, 0x52, 0x00, 0xf9, 0x8e, 0x87, 0xf9, 0x8c, 0x1a, 0x1b, 0x90, 0xe1, 0x78, 0x18,
	0x7d, 0x0d, 0x8d, 0x0d, 0x28, 0xf1, 0xb2, 0x51, 0xd5, 0xd7, 0x98, 0xc4, 0x43, 0xdf, 0x42, 0x6b,
	0x0d, 0xe1, 0x62, 0xb3, 0x81, 0xad, 0xd9, 0xb9, 0xd6, 0xcb, 0x3f, 0x04, 0x90, 0x77, 0x8f, 0x04,
	0xf5, 0xa0, 0x3b, 0xd1, 0x0d, 0x7d, 0xa4, 0x4c, 0x34, 0xfb, 0x6e, 0x3c, 0x35, 0x6d, 0x53, 0x19,
	0x69, 0xf6, 0xbd, 0xa1, 0x6a, 0x3f, 0xe8, 0x86, 0x26, 0x7f, 0x86, 0xba, 0xd0, 0xde, 0x03, 0x18,
	0x6b, 0x8a, 0x2a, 0x0b, 0x2f, 0x14, 0x4d, 0x6b, 0x6a, 0xca, 0xe2, 0x0b, 0xd4, 0xda, 0x8f, 0x37,
	0x63, 0xc5, 0x18, 0x69, 0x72, 0xe9, 0xf2, 0x17, 0x68, 0xef, 0xde, 0x1c, 0xf1, 0xd2, 0xb6, 0x4e,
	0xe0, 0x78, 0xfd, 0x96, 0xd1, 0x6d, 0x77, 0x74, 0x0c, 0xa8, 0x58, 0x1b, 0x4f, 0xef, 0x2d, 0x59,
	0x40, 0x5f, 0xc2, 0xe7, 0xc5, 0xbc, 0xaa, 0x3c, 0xc8, 0x22, 0x6a, 0xc3, 0x51, 0x31, 0x3d, 0x99,
	0x1a, 0xb3, 0xb1, 0x5c, 0xba, 0xfc, 0x55, 0x80, 0xa3, 0x3d, 0x37, 0x8f, 0xce, 0xa1, 0x57, 0x7c,
	0xa0, 0xa8, 0xaa, 0x3d, 0x7b, 0x30, 0x0b, 0x63, 0xd9, 0x16, 0x57, 0x04, 0x31, 0xa9, 0xb2, 0xf0,
	0x0a, 0xcb, 0x7a, 0x02, 0xe2, 0xc7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x74, 0x12, 0xe9, 0x88, 0xdd,
	0x07, 0x00, 0x00,
}
